//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BussinessERPDbEntities1 : DbContext
    {
        public BussinessERPDbEntities1()
            : base("name=BussinessERPDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblAccountActivity> tblAccountActivities { get; set; }
        public virtual DbSet<tblAccountControl> tblAccountControls { get; set; }
        public virtual DbSet<tblAccountHead> tblAccountHeads { get; set; }
        public virtual DbSet<tblAccountSetting> tblAccountSettings { get; set; }
        public virtual DbSet<tblAccountSubControl> tblAccountSubControls { get; set; }
        public virtual DbSet<tblAgent> tblAgents { get; set; }
        public virtual DbSet<tblBranch> tblBranches { get; set; }
        public virtual DbSet<tblBranchType> tblBranchTypes { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblCity> tblCities { get; set; }
        public virtual DbSet<tblCompany> tblCompanies { get; set; }
        public virtual DbSet<tblCountry> tblCountries { get; set; }
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblCustomerInvoice> tblCustomerInvoices { get; set; }
        public virtual DbSet<tblCustomerInvoiceDetail> tblCustomerInvoiceDetails { get; set; }
        public virtual DbSet<tblCustomerPayment> tblCustomerPayments { get; set; }
        public virtual DbSet<tblCustomerReturnInvoice> tblCustomerReturnInvoices { get; set; }
        public virtual DbSet<tblCustomerReturnInvoiceDetail> tblCustomerReturnInvoiceDetails { get; set; }
        public virtual DbSet<tblCustomerReturnPayment> tblCustomerReturnPayments { get; set; }
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
        public virtual DbSet<tblFinancialYear> tblFinancialYears { get; set; }
        public virtual DbSet<tblPayroll> tblPayrolls { get; set; }
        public virtual DbSet<tblPurchaseCartDetail> tblPurchaseCartDetails { get; set; }
        public virtual DbSet<tblSaleCartDetail> tblSaleCartDetails { get; set; }
        public virtual DbSet<tblState> tblStates { get; set; }
        public virtual DbSet<tblStock> tblStocks { get; set; }
        public virtual DbSet<tblSupplier> tblSuppliers { get; set; }
        public virtual DbSet<tblSupplierInvoice> tblSupplierInvoices { get; set; }
        public virtual DbSet<tblSupplierInvoiceDetail> tblSupplierInvoiceDetails { get; set; }
        public virtual DbSet<tblSupplierPayment> tblSupplierPayments { get; set; }
        public virtual DbSet<tblSupplierReturnInvoice> tblSupplierReturnInvoices { get; set; }
        public virtual DbSet<tblSupplierReturnInvoiceDetail> tblSupplierReturnInvoiceDetails { get; set; }
        public virtual DbSet<tblSupplierReturnPayment> tblSupplierReturnPayments { get; set; }
        public virtual DbSet<tblTransaction> tblTransactions { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUserType> tblUserTypes { get; set; }
    }
}
