//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCountry
    {
        public int CountryID { get; set; }
        public string CountryName { get; set; }
        public string Photo { get; set; }
        public string Title { get; set; }
        public string Keyword { get; set; }
        public int UserID { get; set; }
    }
}
